theme: jekyll-theme-cayman
title: The Process of MBO 
description: Management by objectives refers to a formal set of procedures regarding to managing an organisation that begins with goal setting and continues through performance review.
