theme: jekyll-theme-cayman
author: By Group 7 (HCC Bcom. 1st Sem)
title: Management By Objectives (MBO)
description: Management by objectives refers to a formal set of procedures regarding to managing an organisation that begins with goal setting and continues through performance review.
